# Generated by Django 6.0.6 on 2026-07-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Designed & Built in Kerala', max_length=200)),
                ('heading', models.CharField(default='Pools shaped<br>around how you live', help_text='Use <br> for a line break, same as the original hero heading.', max_length=300)),
                ('sub', models.TextField(default='From drone-surveyed site plans to the last pool light installed — custom swimming pools, renovations and premium accessories, delivered as one seamless build.')),
                ('video_url', models.URLField(blank=True, default='https://cdn.coverr.co/videos/coverr-aerial-view-of-a-swimming-pool-2633/1080p.mp4')),
                ('poster_image', models.URLField(blank=True, default='https://images.unsplash.com/photo-1572331165267-854da2b10ccf?q=80&w=1600&auto=format&fit=crop')),
                ('stat1_value', models.CharField(default='240+', max_length=20)),
                ('stat1_label', models.CharField(default='Pools Built', max_length=40)),
                ('stat2_value', models.CharField(default='4.9★', max_length=20)),
                ('stat2_label', models.CharField(default='Client Rating', max_length=40)),
                ('stat3_value', models.CharField(default='12 Yrs', max_length=20)),
                ('stat3_label', models.CharField(default='Experience', max_length=40)),
                ('stat4_value', models.CharField(default='60+', max_length=20)),
                ('stat4_label', models.CharField(default='Accessories', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('pool', 'Pool Designs'), ('pump', 'Pumps & Filters'), ('light', 'Lighting'), ('cover', 'Covers & Ladders'), ('clean', 'Cleaning')], default='pool', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField(blank=True, null=True, verbose_name='MRP (strikethrough price)')),
                ('sizes', models.CharField(help_text='Comma separated, e.g. 20x10 ft, 25x12 ft', max_length=300)),
                ('image_url', models.URLField(blank=True, help_text='Use this OR upload a file below.', null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_whatsapp', models.CharField(default='917356462150', help_text='Country code + number, digits only, no + or spaces. e.g. 917356462150', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pools.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reviews/')),
                ('is_video', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pools.review')),
            ],
        ),
    ]
